# Generated by Django 3.2.13 on 2022-04-13 01:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.UUIDField(default=uuid.uuid4, help_text='Tracking number')),
                ('description', models.TextField(blank=True, default='', help_text='Shipment description')),
                ('sender_address', models.TextField(help_text='Sender address')),
                ('recipient_address', models.TextField(help_text='Recipient address')),
                ('date_sent', models.DateTimeField(help_text='Parcel send date')),
                ('date_delivered', models.DateTimeField(blank=True, default=None, help_text='Parcel delivery date', null=True)),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-date_sent'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['track_number'], name='shipments_s_track_n_4e3329_idx'),
        ),
    ]
